import { useEffect, useMemo, useRef } from "react";
import { useFrame, useThree } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { deriveDepthPalette } from "./themePalette";
import { usePerf } from "../perf.jsx";

// ---------------------------------------------------------------------------
// TreeModel3D — the real scanned/generated branch mesh (public/models/
// tree-branch.glb) rendered not as solid/holographic geometry but as a
// dense cloud of tiny glowing particles sampled across its own surface —
// the same "made of light-dust" language as the DNA helix model
// (see DnaHelixModel.jsx) applied to the tree's shape, so the two read as
// one visual family: additive-blended points, a warm near/far theme tint,
// a bright crest-color pulse riding the growth front, and a soft per-
// particle twinkle instead of a lit, filled surface.
//
// The source mesh has no branch hierarchy, no material, no UVs — just one
// static triangle soup. Dust points are generated by scattering random
// samples across each triangle, weighted by that triangle's area, so
// density stays roughly uniform across the whole surface no matter how
// big or small individual triangles are. Each dust point inherits:
//   - a barycentrically-interpolated "grow value" (0 at the root, 1 at the
//     highest point, plus per-vertex hash jitter) from the mesh's own
//     per-vertex growth attribute, so scroll-driven growth reveals the
//     dust cloud from the ground up exactly like the old solid version did
//   - the owning triangle's face normal, for a cheap fixed-light diffuse
//     term that gives the cloud some sense of volume/shading instead of
//     reading as a flat scatter
//   - a random per-particle seed driving size, twinkle phase, and flutter
//
// Render passes:
//   1. dust points — the entire tree, as small additive glow dots
// ---------------------------------------------------------------------------

const MODEL_URL = "/models/tree-branch.glb";
const MIN_VISIBLE_FRACTION = 0.035; // small rooted stub already lit on load
const EDGE_WIDTH = 0.05; // normalized-height softness of the growing front
const GROW_NOISE_AMOUNT = 0.05; // how jagged the growth front looks
const DUST_PARTICLES_PER_TREE = 26000; // total tiny particles the tree is "made of", at full ("high") quality
// The dust cloud is the single biggest per-tree cost in this scene (every
// point is a shader-driven vertex), so it's the one that scales hardest
// with device tier — a weak GPU gets a noticeably sparser tree rather than
// dropping frames trying to render 26k points per tree.
const DUST_TIER_SCALE = { low: 0.15, medium: 0.45, high: 1 };
const DUST_SIZE_MIN = 2.4;
const DUST_SIZE_RANGE = 2.6;
const DUST_PIXEL_SCALE = 900.0; // point-size distance-falloff constant, tuned so DUST_SIZE_MIN/RANGE read as visible dust motes at this scene's camera distance

// Leaf/dust hover reaction — all in the points geometry's own local units
// (the model is normalized to 1 unit tall, so e.g. 0.09 ≈ 9% of tree height,
// which scales naturally with however big the tree renders on screen).
const HOVER_RADIUS = 0.1; // how close the cursor needs to be to affect dust
const HOVER_PUSH = 0.05; // outward drift amount at the cursor's center
const HOVER_FLUTTER = 0.02; // extra shake/flutter amplitude while hovered
const HOVER_SIZE_BOOST = 0.6; // how much bigger hovered dust gets

function clamp(v, min, max) {
  return Math.max(min, Math.min(max, v));
}

// Cheap deterministic hash (not real noise, doesn't need to be) so the
// growth front looks hand-grown instead of a laser-flat plane, and so
// per-particle jitter/twinkle stays stable across re-renders.
function hash3(x, y, z) {
  const s = Math.sin(x * 12.9898 + y * 78.233 + z * 37.719) * 43758.5453;
  return s - Math.floor(s);
}

function buildDustMaterial() {
  return new THREE.ShaderMaterial({
    transparent: true,
    depthWrite: false,
    blending: THREE.AdditiveBlending,
    uniforms: {
      uProgress: { value: 0 },
      uEdgeWidth: { value: EDGE_WIDTH },
      uNear: { value: new THREE.Color() },
      uFar: { value: new THREE.Color() },
      uCrest: { value: new THREE.Color() },
      uTime: { value: 0 },
      // Cursor position in this points object's own local space (computed
      // each frame on the CPU from the cursor's world position — see the
      // dustPointsRef block in useFrame below — so the shader itself stays
      // simple: just a distance check, no matrix math on the GPU). Starts
      // far away so nothing reacts before the pointer has actually moved.
      uMouseLocal: { value: new THREE.Vector3(9999, 9999, 9999) },
      uHoverRadius: { value: HOVER_RADIUS },
    },
    vertexShader: `
      attribute float aGrow;
      attribute vec3 aNormal2;
      attribute float aSeed;
      attribute float aSize;
      varying float vGrowFade;
      varying float vFront;
      varying float vDiffuse;
      varying float vSeed;
      varying float vHover;
      uniform float uProgress;
      uniform float uEdgeWidth;
      uniform float uTime;
      uniform vec3 uMouseLocal;
      uniform float uHoverRadius;
      void main() {
        float t = clamp((uProgress - aGrow) / uEdgeWidth, 0.0, 1.0);
        vGrowFade = t;
        vFront = exp(-t * 6.0) * step(0.001, t);
        vSeed = aSeed;

        vec3 nrmW = normalize(mat3(modelMatrix) * aNormal2);
        vec3 lightDir = normalize(vec3(0.4, 0.85, 0.55));
        vDiffuse = 0.45 + 0.55 * max(dot(nrmW, lightDir), 0.0);

        // Hover reaction: dust near the cursor drifts outward and flutters,
        // falling off smoothly with distance so it reads as a little cluster
        // stirring rather than one point snapping.
        float dist = distance(position.xy, uMouseLocal.xy);
        float hover = smoothstep(uHoverRadius, 0.0, dist);
        vHover = hover;
        vec2 pushDir = dist > 0.0001 ? normalize(position.xy - uMouseLocal.xy) : vec2(0.0, 1.0);
        float flutter = sin(uTime * 9.0 + aSeed * 31.0) * 0.4 + sin(uTime * 5.3 + aSeed * 11.0) * 0.6;

        vec3 displaced = position;
        displaced.xy += pushDir * hover * ${HOVER_PUSH.toFixed(3)};
        displaced.x += flutter * hover * ${HOVER_FLUTTER.toFixed(3)};
        displaced.y += cos(uTime * 7.0 + aSeed * 17.0) * hover * ${HOVER_FLUTTER.toFixed(3)};

        // Gentle idle twinkle jitter in point size — sells the "cloud of
        // tiny dust motes" feel even when nothing else is moving.
        float twinkle = sin(uTime * (1.5 + aSeed * 2.0) + aSeed * 40.0);

        vec4 mvPosition = modelViewMatrix * vec4(displaced, 1.0);
        float sizeMul = (0.35 + 0.65 * t) * (1.0 + hover * ${HOVER_SIZE_BOOST.toFixed(2)}) * (0.85 + 0.15 * twinkle);
        gl_PointSize = aSize * (${DUST_PIXEL_SCALE.toFixed(1)} / max(-mvPosition.z, 0.001)) * sizeMul;
        gl_Position = projectionMatrix * mvPosition;
      }
    `,
    fragmentShader: `
      uniform vec3 uNear;
      uniform vec3 uFar;
      uniform vec3 uCrest;
      uniform float uTime;
      varying float vGrowFade;
      varying float vFront;
      varying float vDiffuse;
      varying float vSeed;
      varying float vHover;
      void main() {
        if (vGrowFade <= 0.003) discard;
        vec2 uv = gl_PointCoord - vec2(0.5);
        float d = length(uv);
        float core = smoothstep(0.5, 0.0, d);
        if (core <= 0.01) discard;

        vec3 base = mix(uFar, uNear, vDiffuse);
        float twinkle = 0.75 + 0.25 * sin(uTime * (2.0 + vSeed * 3.0) + vSeed * 60.0);
        vec3 color = base * twinkle + uCrest * vFront * 1.3 + uCrest * vHover * 0.6;

        float alpha = core * vGrowFade * (0.75 + vFront * 0.6 + vHover * 0.35);
        gl_FragColor = vec4(color, clamp(alpha, 0.0, 1.0));
      }
    `,
  });
}

// Adds the per-vertex "grow value" attribute once (shared geometry is
// cached by useGLTF across both the left and right tree instances — the
// attribute only needs computing the first time).
function ensureGrowAttribute(geometry) {
  if (geometry.getAttribute("aGrow")) return;
  const pos = geometry.getAttribute("position");
  const grow = new Float32Array(pos.count);
  for (let i = 0; i < pos.count; i++) {
    const x = pos.getX(i);
    const y = pos.getY(i);
    const z = pos.getZ(i);
    const noise = hash3(x * 7.1, y * 5.3, z * 6.7) - 0.5;
    grow[i] = clamp(y + noise * GROW_NOISE_AMOUNT, 0, 1.15);
  }
  geometry.setAttribute("aGrow", new THREE.BufferAttribute(grow, 1));
}

// Scatters `totalParticles` points across the mesh's own triangles,
// weighted by triangle area so density stays roughly uniform over the
// whole surface. Each point inherits a barycentrically-interpolated grow
// value and its triangle's face normal (for the fixed-light shading term).
function buildDustGeometry(geometry, totalParticles) {
  const posAttr = geometry.getAttribute("position");
  const growAttr = geometry.getAttribute("aGrow");
  const index = geometry.index;
  const triCount = index ? index.count / 3 : posAttr.count / 3;

  const getVertexIndex = (tri, corner) =>
    index ? index.getX(tri * 3 + corner) : tri * 3 + corner;

  const pA = new THREE.Vector3();
  const pB = new THREE.Vector3();
  const pC = new THREE.Vector3();
  const ab = new THREE.Vector3();
  const ac = new THREE.Vector3();
  const cross = new THREE.Vector3();

  const areas = new Float32Array(triCount);
  let totalArea = 0;
  for (let t = 0; t < triCount; t++) {
    pA.fromBufferAttribute(posAttr, getVertexIndex(t, 0));
    pB.fromBufferAttribute(posAttr, getVertexIndex(t, 1));
    pC.fromBufferAttribute(posAttr, getVertexIndex(t, 2));
    ab.subVectors(pB, pA);
    ac.subVectors(pC, pA);
    const area = cross.crossVectors(ab, ac).length() * 0.5;
    areas[t] = area;
    totalArea += area;
  }

  const perTri = new Int32Array(triCount);
  let allocated = 0;
  for (let t = 0; t < triCount; t++) {
    const c = totalArea > 0 ? Math.round((areas[t] / totalArea) * totalParticles) : 0;
    perTri[t] = c;
    allocated += c;
  }

  const positions = new Float32Array(allocated * 3);
  const growOut = new Float32Array(allocated);
  const normalsOut = new Float32Array(allocated * 3);
  const seeds = new Float32Array(allocated);
  const sizes = new Float32Array(allocated);

  let idx = 0;
  for (let t = 0; t < triCount; t++) {
    const c = perTri[t];
    if (c === 0) continue;
    const ia = getVertexIndex(t, 0);
    const ib = getVertexIndex(t, 1);
    const ic = getVertexIndex(t, 2);
    pA.fromBufferAttribute(posAttr, ia);
    pB.fromBufferAttribute(posAttr, ib);
    pC.fromBufferAttribute(posAttr, ic);
    ab.subVectors(pB, pA);
    ac.subVectors(pC, pA);
    cross.crossVectors(ab, ac).normalize();
    const gA = growAttr.getX(ia);
    const gB = growAttr.getX(ib);
    const gC = growAttr.getX(ic);

    for (let s = 0; s < c; s++) {
      let u = Math.random();
      let v = Math.random();
      if (u + v > 1) {
        u = 1 - u;
        v = 1 - v;
      }
      const w = 1 - u - v;
      const x = pA.x * w + pB.x * u + pC.x * v;
      const y = pA.y * w + pB.y * u + pC.y * v;
      const z = pA.z * w + pB.z * u + pC.z * v;

      positions[idx * 3] = x;
      positions[idx * 3 + 1] = y;
      positions[idx * 3 + 2] = z;
      growOut[idx] = gA * w + gB * u + gC * v;
      normalsOut[idx * 3] = cross.x;
      normalsOut[idx * 3 + 1] = cross.y;
      normalsOut[idx * 3 + 2] = cross.z;
      const seed = hash3(x * 13.1 + t * 0.7, y * 7.7 + s * 0.3, z * 5.3);
      seeds[idx] = seed;
      sizes[idx] = DUST_SIZE_MIN + seed * DUST_SIZE_RANGE;
      idx++;
    }
  }

  const geo = new THREE.BufferGeometry();
  geo.setAttribute("position", new THREE.BufferAttribute(positions, 3));
  geo.setAttribute("aGrow", new THREE.BufferAttribute(growOut, 1));
  geo.setAttribute("aNormal2", new THREE.BufferAttribute(normalsOut, 3));
  geo.setAttribute("aSeed", new THREE.BufferAttribute(seeds, 1));
  geo.setAttribute("aSize", new THREE.BufferAttribute(sizes, 1));
  return geo;
}

export default function TreeModel3D({ colors, reduceMotion }) {
  const { scene } = useGLTF(MODEL_URL);
  const { tier } = usePerf();
  const dustParticleCount = Math.round(
    DUST_PARTICLES_PER_TREE * (DUST_TIER_SCALE[tier] ?? DUST_TIER_SCALE.medium)
  );
  const groupRef = useRef(null);
  const dustPointsRef = useRef(null);
  const swayPhase = useRef(Math.random() * Math.PI * 2);
  const { invalidate } = useThree();

  // Cursor position in world space (viewport-center-relative, same 1
  // world-unit = 1 CSS-pixel convention the camera rig in ScrollTrees.jsx
  // uses), tracked via a plain ref so mouse movement never triggers a
  // React re-render — just read each frame in useFrame below. This is a
  // window-level listener rather than an onPointerMove on the canvas: the
  // tree layer stays pointer-events:none (see ScrollTrees.css) so it can
  // never block clicks/scrolling anywhere on the page, and this still
  // reacts to the cursor everywhere on screen, not just where the canvas
  // happens to be hit-testable.
  const mouseWorld = useRef({ x: 1e6, y: 1e6 });
  const tmpMatrix = useRef(new THREE.Matrix4());
  const tmpVec = useRef(new THREE.Vector3());

  useEffect(() => {
    function onPointerMove(e) {
      mouseWorld.current.x = e.clientX - window.innerWidth / 2;
      mouseWorld.current.y = -(e.clientY - window.innerHeight / 2);
    }
    function onPointerLeave() {
      mouseWorld.current.x = 1e6;
      mouseWorld.current.y = 1e6;
    }
    window.addEventListener("pointermove", onPointerMove, { passive: true });
    document.addEventListener("pointerleave", onPointerLeave);
    return () => {
      window.removeEventListener("pointermove", onPointerMove);
      document.removeEventListener("pointerleave", onPointerLeave);
    };
  }, []);

  const geometry = useMemo(() => {
    let found = null;
    scene.traverse((child) => {
      if (!found && child.isMesh) found = child.geometry;
    });
    if (found) ensureGrowAttribute(found);
    return found;
  }, [scene]);

  const dustGeometry = useMemo(
    () => (geometry ? buildDustGeometry(geometry, dustParticleCount) : null),
    [geometry, dustParticleCount]
  );

  const dustMaterial = useMemo(() => buildDustMaterial(), []);

  useEffect(() => {
    return () => {
      dustMaterial.dispose();
      if (dustGeometry) dustGeometry.dispose();
    };
  }, [dustMaterial, dustGeometry]);

  // Re-tint on theme change.
  useEffect(() => {
    const palette = deriveDepthPalette(colors[0]);
    const near = new THREE.Color(palette.near.r, palette.near.g, palette.near.b);
    const far = new THREE.Color(palette.far.r, palette.far.g, palette.far.b);
    const crest = new THREE.Color(palette.crest.r, palette.crest.g, palette.crest.b);
    dustMaterial.uniforms.uNear.value.copy(near);
    dustMaterial.uniforms.uFar.value.copy(far);
    dustMaterial.uniforms.uCrest.value.copy(crest);
    invalidate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [colors]);

  // Scroll-driven growth, same easing/baseline as before.
  const applyGrowth = () => {
    const scrollable = document.documentElement.scrollHeight - window.innerHeight;
    const progress = scrollable > 0 ? clamp(window.scrollY / scrollable, 0, 1) : 0;
    const eased = 1 - Math.pow(1 - progress, 1.6);
    const grown = MIN_VISIBLE_FRACTION + eased * (1 - MIN_VISIBLE_FRACTION);
    const target = grown + EDGE_WIDTH; // let the soft edge fully resolve by top

    dustMaterial.uniforms.uProgress.value = target;
    invalidate();
  };

  useEffect(() => {
    let rafId = null;
    function onScroll() {
      if (rafId == null) rafId = requestAnimationFrame(() => {
        applyGrowth();
        rafId = null;
      });
    }
    applyGrowth();
    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll, { passive: true });
    return () => {
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
      if (rafId != null) cancelAnimationFrame(rafId);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Idle sway (sells the "real 3D model" feel between scroll events), the
  // shimmer clock for the twinkle/growth-front pulse, and the dust hover
  // reaction.
  useFrame(({ clock }) => {
    if (reduceMotion) return;
    const t = clock.elapsedTime;
    dustMaterial.uniforms.uTime.value = t;
    if (groupRef.current) {
      groupRef.current.rotation.y = Math.sin(t * 0.14 + swayPhase.current) * 0.03;
      groupRef.current.rotation.z = Math.sin(t * 0.1 + swayPhase.current) * 0.008;
    }

    // Project the cursor's world-space position down into this points
    // object's own local space (undoing this tree's specific position/
    // scale/rotation/mirroring in one matrix invert) so the shader itself
    // only ever needs a simple local-space distance check.
    if (dustPointsRef.current) {
      tmpMatrix.current.copy(dustPointsRef.current.matrixWorld).invert();
      tmpVec.current.set(mouseWorld.current.x, mouseWorld.current.y, 0).applyMatrix4(tmpMatrix.current);
      dustMaterial.uniforms.uMouseLocal.value.copy(tmpVec.current);
    }
  });

  if (!geometry || !dustGeometry) return null;

  return (
    <group ref={groupRef}>
      <points ref={dustPointsRef} geometry={dustGeometry} material={dustMaterial} />
    </group>
  );
}

useGLTF.preload(MODEL_URL);

// ---------------------------------------------------------------------------
// Provenance note: public/models/tree-branch.glb is a decimated version of
// the uploaded white_mesh.glb (529k tris / 264k verts, no normals, no
// material — a raw trimesh export). It was grid-cluster decimated to ~45k
// tris, recentered so x/z straddle 0 and the lowest point sits at y=0, then
// uniformly rescaled to exactly 1 unit tall, with smooth vertex normals
// computed from the surviving faces. If you'd rather regenerate this
// yourself (e.g. from a fresher scan) with proper quadric-error decimation
// instead of grid clustering, gltf-transform's `simplify` command or
// Blender's Decimate modifier both work well — just keep the same
// convention (root at y=0, unit height, centered x/z) so it drops in here
// without touching TreeModel3D.jsx or ScrollTrees.jsx.
// ---------------------------------------------------------------------------
